from datetime import UTC, datetime

from app.models.data_platform import (
    AccessibleHiveTable,
    AccessPath,
    AdminAllocationItem,
    AdminAttentionItem,
    AdminCapabilities,
    AdminControlPlaneResponse,
    AdminHiveAccessItem,
    AdminIntegrationStatus,
    AdminPlatformSummary,
    AdminPublishedUpdate,
    DataAccessSummary,
    MorningIngestionStatus,
    PortalPrincipal,
    SourceFreshness,
    UserDataAccessResponse,
    YarnQueueStatus,
)

BUSINESS_DATE = "26 Aug 2026"
OBSERVED_AT = "26 Aug 2026, 08:12 GST"


def _ingestion(
    status: str,
    label: str,
    summary: str,
    *,
    completed_at: str | None = None,
    sla_state: str = "within_sla",
) -> MorningIngestionStatus:
    return MorningIngestionStatus(
        business_date=BUSINESS_DATE,
        status=status,
        status_label=label,
        scheduled_for="06:30 GST",
        completed_at=completed_at,
        last_successful_business_date=(BUSINESS_DATE if status == "succeeded" else "25 Aug 2026"),
        sla_state=sla_state,
        summary=summary,
    )


def _table(
    database: str,
    table: str,
    owner_team: str,
    ldap_group: str,
    access_team: str,
    privilege: str,
    ingestion: MorningIngestionStatus,
) -> AccessibleHiveTable:
    fully_qualified_name = f"{database}.{table}"
    return AccessibleHiveTable(
        id=fully_qualified_name.replace(".", "-"),
        database=database,
        table=table,
        fully_qualified_name=fully_qualified_name,
        owner_team=owner_team,
        access=AccessPath(
            ldap_group=ldap_group,
            team=access_team,
            privilege=privilege,
            policy_name=f"ranger-{database}-{access_team.lower().replace(' ', '-')}",
        ),
        ingestion=ingestion,
    )


def _queue(
    queue_id: str,
    path: str,
    team: str,
    ldap_group: str,
    state: str,
    status: str,
    used: int,
    configured: int,
    running: int,
    pending: int,
    allocated_memory: int,
    pending_memory: int,
) -> YarnQueueStatus:
    return YarnQueueStatus(
        id=queue_id,
        queue_path=path,
        team=team,
        ldap_group=ldap_group,
        state=state,
        status=status,
        used_capacity_percentage=used,
        configured_capacity_percentage=configured,
        running_applications=running,
        pending_applications=pending,
        allocated_memory_gb=allocated_memory,
        pending_memory_gb=pending_memory,
        observed_at=OBSERVED_AT,
    )


class DataPlatformService:
    def __init__(self) -> None:
        self._user_tables = [
            _table(
                "customer",
                "customer_features",
                "Customer Data Products",
                "DSP-CUSTOMER-ANALYTICS",
                "Customer Analytics",
                "SELECT",
                _ingestion(
                    "succeeded",
                    "Complete",
                    "Morning ingestion completed within SLA.",
                    completed_at="06:18 GST",
                ),
            ),
            _table(
                "customer",
                "customer_segments",
                "Customer Data Products",
                "DSP-CUSTOMER-ANALYTICS",
                "Customer Analytics",
                "SELECT",
                _ingestion(
                    "succeeded",
                    "Complete",
                    "Morning ingestion completed within SLA.",
                    completed_at="06:22 GST",
                ),
            ),
            _table(
                "risk",
                "customer_risk_scores",
                "Risk Data",
                "DSP-RISK-CONSUMERS",
                "Customer Analytics",
                "SELECT",
                _ingestion(
                    "late",
                    "Late",
                    "Ingestion completed after the morning SLA.",
                    completed_at="07:04 GST",
                    sla_state="breached",
                ),
            ),
            _table(
                "finance",
                "daily_transactions",
                "Finance Data",
                "DSP-FINANCE-READERS",
                "Customer Analytics",
                "SELECT",
                _ingestion(
                    "failed",
                    "Failed",
                    "The morning ingestion failed and is being investigated.",
                    sla_state="breached",
                ),
            ),
            _table(
                "reference",
                "product_hierarchy",
                "Enterprise Reference Data",
                "DSP-REFERENCE-READERS",
                "Customer Analytics",
                "SELECT",
                _ingestion(
                    "succeeded",
                    "Complete",
                    "Morning ingestion completed within SLA.",
                    completed_at="05:54 GST",
                ),
            ),
            _table(
                "digital",
                "web_events",
                "Digital Analytics",
                "DSP-DIGITAL-CONSUMERS",
                "Customer Analytics",
                "SELECT",
                _ingestion(
                    "pending", "In progress", "Morning ingestion is still running.", sla_state="at_risk"
                ),
            ),
            _table(
                "customer",
                "churn_features",
                "Customer Data Products",
                "DSP-CUSTOMER-ANALYTICS",
                "Customer Analytics",
                "SELECT",
                _ingestion(
                    "succeeded",
                    "Complete",
                    "Morning ingestion completed within SLA.",
                    completed_at="06:09 GST",
                ),
            ),
            _table(
                "marketing",
                "campaign_response",
                "Marketing Data",
                "DSP-MARKETING-CONSUMERS",
                "Customer Analytics",
                "SELECT",
                _ingestion(
                    "not_received",
                    "Not received",
                    "No morning delivery has been received.",
                    sla_state="breached",
                ),
            ),
        ]

        self._queues = [
            _queue(
                "customer-models",
                "root.analytics.customer_models",
                "Customer Analytics",
                "DSP-CUSTOMER-ANALYTICS",
                "attention",
                "Capacity pressure",
                87,
                30,
                7,
                3,
                356,
                96,
            ),
            _queue(
                "customer-shared",
                "root.analytics.shared",
                "Customer Analytics",
                "DSP-CUSTOMER-ANALYTICS",
                "healthy",
                "Available",
                42,
                20,
                4,
                0,
                128,
                0,
            ),
            _queue(
                "risk-models",
                "root.risk.models",
                "Risk Modelling",
                "DSP-RISK-MODELLERS",
                "healthy",
                "Available",
                39,
                25,
                5,
                0,
                192,
                0,
            ),
            _queue(
                "finance-insights",
                "root.finance.insights",
                "Finance Insights",
                "DSP-FINANCE-ANALYTICS",
                "critical",
                "Queue saturated",
                99,
                20,
                11,
                8,
                508,
                224,
            ),
            _queue(
                "fraud-lab",
                "root.risk.fraud_lab",
                "Fraud Analytics",
                "DSP-FRAUD-ANALYTICS",
                "attention",
                "Pending applications",
                81,
                15,
                8,
                4,
                294,
                120,
            ),
        ]

    def user_access(self, owner_keys: frozenset[str] | None = None) -> UserDataAccessResponse:
        known_user_keys = {"alex-morgan", "alex.morgan", "user-1048"}
        if owner_keys is not None and not known_user_keys.intersection(owner_keys):
            identifier = sorted(owner_keys)[0] if owner_keys else "current-user"
            return UserDataAccessResponse(
                generated_at=datetime.now(UTC),
                principal=PortalPrincipal(
                    id=identifier,
                    enterprise_user_id=identifier,
                    name="DSP user",
                    team="No mapped team",
                    ldap_groups=[],
                ),
                summary=DataAccessSummary(
                    accessible_tables=0,
                    ingested=0,
                    late=0,
                    failed=0,
                    pending=0,
                    business_date=BUSINESS_DATE,
                ),
                tables=[],
                yarn_queues=[],
                source_freshness=[],
            )
        counts = {state: 0 for state in ("succeeded", "late", "failed", "pending", "not_received")}
        for item in self._user_tables:
            counts[item.ingestion.status] += 1

        return UserDataAccessResponse(
            generated_at=datetime.now(UTC),
            principal=PortalPrincipal(
                id="user-1048",
                enterprise_user_id="alex.morgan",
                name="Alex Morgan",
                team="Customer Analytics",
                ldap_groups=[
                    "DSP-CUSTOMER-ANALYTICS",
                    "DSP-RISK-CONSUMERS",
                    "DSP-FINANCE-READERS",
                    "DSP-REFERENCE-READERS",
                    "DSP-DIGITAL-CONSUMERS",
                    "DSP-MARKETING-CONSUMERS",
                ],
            ),
            summary=DataAccessSummary(
                accessible_tables=len(self._user_tables),
                ingested=counts["succeeded"],
                late=counts["late"],
                failed=counts["failed"],
                pending=counts["pending"] + counts["not_received"],
                business_date=BUSINESS_DATE,
            ),
            tables=self._user_tables,
            yarn_queues=[queue for queue in self._queues if queue.team == "Customer Analytics"],
            source_freshness=[
                SourceFreshness(
                    source="LDAP and Ranger access catalogue",
                    status="current",
                    last_synced_at="26 Aug 2026, 07:55 GST",
                    summary="Access metadata is current.",
                ),
                SourceFreshness(
                    source="Morning ingestion monitor",
                    status="current",
                    last_synced_at=OBSERVED_AT,
                    summary="Latest ingestion states received.",
                ),
                SourceFreshness(
                    source="YARN ResourceManager",
                    status="current",
                    last_synced_at="26 Aug 2026, 08:11 GST",
                    summary="Queue metrics updated one minute ago.",
                ),
            ],
        )

    def admin_control_plane(self) -> AdminControlPlaneResponse:
        admin_tables = [
            AdminHiveAccessItem(
                id=item.id,
                database=item.database,
                table=item.table,
                fully_qualified_name=item.fully_qualified_name,
                owner_team=item.owner_team,
                teams=[item.access.team],
                ldap_groups=[item.access.ldap_group],
                user_count={
                    "Customer Analytics": 28,
                    "Risk Modelling": 19,
                    "Finance Insights": 14,
                }.get(item.access.team, 28),
                privileges=[item.access.privilege],
                ingestion=item.ingestion,
            )
            for item in self._user_tables
        ]
        admin_tables.extend(
            [
                AdminHiveAccessItem(
                    id="risk-model-features",
                    database="risk",
                    table="model_features",
                    fully_qualified_name="risk.model_features",
                    owner_team="Risk Data",
                    teams=["Risk Modelling", "Fraud Analytics"],
                    ldap_groups=["DSP-RISK-MODELLERS", "DSP-FRAUD-ANALYTICS"],
                    user_count=37,
                    privileges=["SELECT"],
                    ingestion=_ingestion(
                        "succeeded",
                        "Complete",
                        "Morning ingestion completed within SLA.",
                        completed_at="06:11 GST",
                    ),
                ),
                AdminHiveAccessItem(
                    id="finance-ledger-daily",
                    database="finance",
                    table="ledger_daily",
                    fully_qualified_name="finance.ledger_daily",
                    owner_team="Finance Data",
                    teams=["Finance Insights"],
                    ldap_groups=["DSP-FINANCE-ANALYTICS"],
                    user_count=14,
                    privileges=["SELECT"],
                    ingestion=_ingestion(
                        "pending", "In progress", "Morning ingestion is still running.", sla_state="at_risk"
                    ),
                ),
            ]
        )

        return AdminControlPlaneResponse(
            generated_at=datetime.now(UTC),
            summary=AdminPlatformSummary(
                total_vms=18,
                unhealthy_vms=2,
                active_devspaces=41,
                active_jobs=26,
                governed_tables=len(admin_tables),
                ingestion_attention=sum(item.ingestion.status != "succeeded" for item in admin_tables),
                yarn_queue_attention=sum(queue.state != "healthy" for queue in self._queues),
                active_incidents=2,
                pending_approvals=3,
            ),
            attention_items=[
                AdminAttentionItem(
                    id="attention-finance-ingestion",
                    type="ingestion",
                    severity="critical",
                    title="finance.daily_transactions ingestion failed",
                    summary="Morning delivery missed its SLA; Finance Data is investigating.",
                    owner="Finance Data",
                    occurred_at="07:02 GST",
                    href="#admin/data",
                ),
                AdminAttentionItem(
                    id="attention-finance-yarn",
                    type="yarn_queue",
                    severity="critical",
                    title="Finance Insights YARN queue is saturated",
                    summary="8 applications are pending and 224 GB memory is requested.",
                    owner="Compute Operations",
                    occurred_at="08:11 GST",
                    href="#admin/data",
                ),
                AdminAttentionItem(
                    id="attention-vm-031",
                    type="vm",
                    severity="warning",
                    title="dsp-vm-031 disk utilisation is critical",
                    summary="Three devspaces are at risk on the VM.",
                    owner="DSP DevOps",
                    occurred_at="08:09 GST",
                    href="#vm/vm-031",
                ),
                AdminAttentionItem(
                    id="attention-allocation",
                    type="allocation",
                    severity="information",
                    title="Three VM allocations require approval",
                    summary="Requests have validated LDAP groups and are ready for review.",
                    owner="Platform Administration",
                    occurred_at="07:45 GST",
                    href="#admin",
                ),
            ],
            hive_tables=admin_tables,
            yarn_queues=self._queues,
            integrations=[
                AdminIntegrationStatus(
                    id="ldap",
                    name="Enterprise LDAP",
                    status="healthy",
                    last_successful_sync="07:55 GST",
                    objects_synced=42,
                    summary="Team and group mappings are current.",
                ),
                AdminIntegrationStatus(
                    id="ranger",
                    name="Ranger access catalogue",
                    status="healthy",
                    last_successful_sync="07:56 GST",
                    objects_synced=184,
                    summary="Table entitlements are current.",
                ),
                AdminIntegrationStatus(
                    id="ingestion",
                    name="Morning ingestion monitor",
                    status="degraded",
                    last_successful_sync="08:12 GST",
                    objects_synced=176,
                    summary="Four ingestion states require attention.",
                ),
                AdminIntegrationStatus(
                    id="yarn",
                    name="YARN ResourceManager",
                    status="healthy",
                    last_successful_sync="08:11 GST",
                    objects_synced=15,
                    summary="Queue metrics are current.",
                ),
                AdminIntegrationStatus(
                    id="monitoring",
                    name="VM monitoring",
                    status="degraded",
                    last_successful_sync="08:10 GST",
                    objects_synced=18,
                    summary="Two VMs require attention.",
                ),
                AdminIntegrationStatus(
                    id="remedy",
                    name="Remedy",
                    status="healthy",
                    last_successful_sync="08:06 GST",
                    objects_synced=12,
                    summary="Incident summaries are current.",
                ),
                AdminIntegrationStatus(
                    id="confluence",
                    name="Confluence",
                    status="stale",
                    last_successful_sync="25 Aug, 18:30 GST",
                    objects_synced=68,
                    summary="Content index refresh is delayed.",
                ),
            ],
            allocations=[
                AdminAllocationItem(
                    id="alloc-1042",
                    vm_name="dsp-vm-044",
                    tenant="Analytics",
                    target_team="Customer Analytics",
                    ldap_group="DSP-CUSTOMER-ANALYTICS",
                    status="pending_approval",
                    requested_by="Sara Khan",
                    requested_at="26 Aug, 07:42 GST",
                    summary="Standard development VM allocation.",
                ),
                AdminAllocationItem(
                    id="alloc-1041",
                    vm_name="dsp-vm-045",
                    tenant="Risk",
                    target_team="Fraud Analytics",
                    ldap_group="DSP-FRAUD-ANALYTICS",
                    status="applying",
                    requested_by="Omar Rahman",
                    requested_at="26 Aug, 07:21 GST",
                    approver="Maya Singh",
                    summary="Network and LDAP policies are being applied.",
                ),
                AdminAllocationItem(
                    id="alloc-1038",
                    vm_name="dsp-vm-040",
                    tenant="Finance",
                    target_team="Finance Insights",
                    ldap_group="DSP-FINANCE-ANALYTICS",
                    status="failed",
                    requested_by="Amal Joseph",
                    requested_at="25 Aug, 15:06 GST",
                    approver="Maya Singh",
                    summary="IP allocation validation failed.",
                ),
                AdminAllocationItem(
                    id="alloc-1035",
                    vm_name="dsp-vm-039",
                    tenant="Risk",
                    target_team="Risk Modelling",
                    ldap_group="DSP-RISK-MODELLERS",
                    status="active",
                    requested_by="Omar Rahman",
                    requested_at="25 Aug, 10:14 GST",
                    approver="Maya Singh",
                    summary="Allocation completed and verified.",
                ),
            ],
            updates=[
                AdminPublishedUpdate(
                    id="update-209",
                    type="maintenance",
                    title="Hadoop maintenance window",
                    service="Hadoop",
                    state="scheduled",
                    owner="Data Platform Operations",
                    effective_at="02 Sep, 22:00 GST",
                    audience="All Hadoop users",
                ),
                AdminPublishedUpdate(
                    id="update-208",
                    type="support",
                    title="Weekend support roster",
                    service="DSP Support",
                    state="published",
                    owner="DSP DevOps",
                    effective_at="30 Aug, 08:00 GST",
                    audience="All DSP users",
                ),
                AdminPublishedUpdate(
                    id="update-207",
                    type="troubleshooting",
                    title="Resolve expired CyberArk sessions",
                    service="CyberArk",
                    state="in_review",
                    owner="Identity Operations",
                    effective_at="28 Aug, 12:00 GST",
                    audience="CyberArk users",
                ),
                AdminPublishedUpdate(
                    id="update-205",
                    type="documentation",
                    title="Python 3.12 image migration guide",
                    service="Nexus",
                    state="draft",
                    owner="Developer Experience",
                    effective_at="04 Sep, 09:00 GST",
                    audience="Devspace owners",
                ),
            ],
            capabilities=AdminCapabilities(
                read_only_preview=True,
                allocation_workflow_enabled=False,
                content_workflow_enabled=False,
                requires_enterprise_sso=True,
            ),
        )
