"""create authentication schema

Revision ID: c8a59245527f
Revises:
Create Date: 2026-08-26 21:11:26.738313
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c8a59245527f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authentication_audit_event",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("outcome", sa.String(length=30), nullable=False),
        sa.Column("principal_id", sa.String(length=36), nullable=True),
        sa.Column("username", sa.String(length=160), nullable=True),
        sa.Column("source_ip", sa.String(length=80), nullable=True),
        sa.Column("detail", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_authentication_audit_event_created_at"),
        "authentication_audit_event",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_authentication_audit_event_event_type"),
        "authentication_audit_event",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_authentication_audit_event_principal_id"),
        "authentication_audit_event",
        ["principal_id"],
        unique=False,
    )
    op.create_table(
        "principal",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=160), nullable=False),
        sa.Column("display_name", sa.String(length=240), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("enterprise_user_id", sa.String(length=160), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("authentication_source", sa.String(length=24), nullable=False),
        sa.Column("authorization_version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_principal_enterprise_user_id"), "principal", ["enterprise_user_id"], unique=False
    )
    op.create_index(op.f("ix_principal_role"), "principal", ["role"], unique=False)
    op.create_index(op.f("ix_principal_username"), "principal", ["username"], unique=True)
    op.create_table(
        "saml_assertion_replay",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("issuer", sa.String(length=500), nullable=False),
        sa.Column("assertion_id", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("issuer", "assertion_id", name="uq_saml_assertion_replay"),
    )
    op.create_index("ix_saml_replay_expiry", "saml_assertion_replay", ["expires_at"], unique=False)
    op.create_table(
        "saml_login_transaction",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("relay_state_hash", sa.String(length=64), nullable=False),
        sa.Column("saml_request_id", sa.String(length=255), nullable=False),
        sa.Column("login_nonce_hash", sa.String(length=64), nullable=False),
        sa.Column("return_path", sa.String(length=500), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_saml_login_transaction_expires_at"), "saml_login_transaction", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_saml_login_transaction_relay_state_hash"),
        "saml_login_transaction",
        ["relay_state_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_saml_login_transaction_saml_request_id"),
        "saml_login_transaction",
        ["saml_request_id"],
        unique=True,
    )
    op.create_table(
        "auth_exchange_code",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("principal_id", sa.String(length=36), nullable=False),
        sa.Column("login_nonce_hash", sa.String(length=64), nullable=False),
        sa.Column("return_path", sa.String(length=500), nullable=False),
        sa.Column("authenticated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["principal_id"], ["principal.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_exchange_code_code_hash"), "auth_exchange_code", ["code_hash"], unique=True)
    op.create_index(
        op.f("ix_auth_exchange_code_expires_at"), "auth_exchange_code", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_auth_exchange_code_principal_id"), "auth_exchange_code", ["principal_id"], unique=False
    )
    op.create_table(
        "auth_refresh_session",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("principal_id", sa.String(length=36), nullable=False),
        sa.Column("session_secret_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_secret_hash", sa.String(length=64), nullable=False),
        sa.Column("authentication_provider", sa.String(length=24), nullable=False),
        sa.Column("authenticated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["principal_id"], ["principal.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_auth_refresh_session_expires_at"), "auth_refresh_session", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_auth_refresh_session_principal_id"), "auth_refresh_session", ["principal_id"], unique=False
    )
    op.create_index(
        op.f("ix_auth_refresh_session_session_secret_hash"),
        "auth_refresh_session",
        ["session_secret_hash"],
        unique=True,
    )
    op.create_table(
        "local_account",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("principal_id", sa.String(length=36), nullable=False),
        sa.Column("normalized_username", sa.String(length=160), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("failed_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["principal_id"], ["principal.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_local_account_normalized_username"), "local_account", ["normalized_username"], unique=True
    )
    op.create_index(op.f("ix_local_account_principal_id"), "local_account", ["principal_id"], unique=True)
    op.create_table(
        "principal_identity",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("principal_id", sa.String(length=36), nullable=False),
        sa.Column("identity_provider", sa.String(length=80), nullable=False),
        sa.Column("external_object_id", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=320), nullable=False),
        sa.Column("issuer", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_authenticated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["principal_id"], ["principal.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identity_provider", "external_object_id", name="uq_identity_external"),
    )
    op.create_index(
        op.f("ix_principal_identity_principal_id"), "principal_identity", ["principal_id"], unique=False
    )
    op.create_table(
        "local_password_action",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("local_account_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("performed_by_principal_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["local_account_id"], ["local_account.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["performed_by_principal_id"], ["principal.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("local_password_action")
    op.drop_index(op.f("ix_principal_identity_principal_id"), table_name="principal_identity")
    op.drop_table("principal_identity")
    op.drop_index(op.f("ix_local_account_principal_id"), table_name="local_account")
    op.drop_index(op.f("ix_local_account_normalized_username"), table_name="local_account")
    op.drop_table("local_account")
    op.drop_index(op.f("ix_auth_refresh_session_session_secret_hash"), table_name="auth_refresh_session")
    op.drop_index(op.f("ix_auth_refresh_session_principal_id"), table_name="auth_refresh_session")
    op.drop_index(op.f("ix_auth_refresh_session_expires_at"), table_name="auth_refresh_session")
    op.drop_table("auth_refresh_session")
    op.drop_index(op.f("ix_auth_exchange_code_principal_id"), table_name="auth_exchange_code")
    op.drop_index(op.f("ix_auth_exchange_code_expires_at"), table_name="auth_exchange_code")
    op.drop_index(op.f("ix_auth_exchange_code_code_hash"), table_name="auth_exchange_code")
    op.drop_table("auth_exchange_code")
    op.drop_index(op.f("ix_saml_login_transaction_saml_request_id"), table_name="saml_login_transaction")
    op.drop_index(op.f("ix_saml_login_transaction_relay_state_hash"), table_name="saml_login_transaction")
    op.drop_index(op.f("ix_saml_login_transaction_expires_at"), table_name="saml_login_transaction")
    op.drop_table("saml_login_transaction")
    op.drop_index("ix_saml_replay_expiry", table_name="saml_assertion_replay")
    op.drop_table("saml_assertion_replay")
    op.drop_index(op.f("ix_principal_username"), table_name="principal")
    op.drop_index(op.f("ix_principal_role"), table_name="principal")
    op.drop_index(op.f("ix_principal_enterprise_user_id"), table_name="principal")
    op.drop_table("principal")
    op.drop_index(op.f("ix_authentication_audit_event_principal_id"), table_name="authentication_audit_event")
    op.drop_index(op.f("ix_authentication_audit_event_event_type"), table_name="authentication_audit_event")
    op.drop_index(op.f("ix_authentication_audit_event_created_at"), table_name="authentication_audit_event")
    op.drop_table("authentication_audit_event")
    # ### end Alembic commands ###
